### ISSUE TITLE
Enchanting quest items

### ISSUE THREAD

**Issue by leobolin** [p3lim-wow/LibProcessable#13]
Hi! There are a bunch of items that are disenchantable during Enchanting quests that I think should be whitelisted for disenchanting. Example: [Enchanted Raven Sigil](http://www.wowhead.com/item=137221/enchanted-raven-sigil)

**Comment by p3lim** [comment]
Get me a list of items and I'll see what I can do.

**Comment by leobolin** [comment]
- Highmountain Armor - 137195
- Enchanted Raven Sigil - 137221
- Fel-Crusted Rune - 137286
