### ISSUE TITLE
Issues with Wow Classic 1.13.3 32790 Dec 9 2019 Client

### ISSUE THREAD

**Issue by lycano** [p3lim-wow/LibProcessable#29]
https://github.com/p3lim-wow/LibProcessable/blob/5519f7b3d0f64dffe12b100877ccd4eaa70d3da0/LibProcessable.lua#L9

Current build number for classic is now 11303. I usually would PR a fix but this is just silly ;)
Can you please update the build number and rebuild Molinari?

Best wishes,
lycano

(Edit: Just noticed same author :D sorry about that)

**Comment by lycano** [comment]
I didnt test this with retail but i found out that you might be able to use GetClientDisplayExpansionLevel() which should always return 0 (Classic) for Classic Client. I didnt test what this function would return in lets say legion but maybe you know?

If there is no real reason to let the addon break every tocversion change then maybe use this function instead?

**Comment by rainfordays** [comment]
One could also read the agentUID from CVars, in classic it's "wow_classic"

**Comment by p3lim** [comment]
Fixed in #30.
