### ISSUE TITLE
Redeemer's Mace not disenchantable

### ISSUE THREAD

**Issue by leobolin** [p3lim-wow/LibProcessable#40]
First of all I realize this *might* be a bug with Molinari, but I wasn't sure how to tell which part of the addon is the culprit,

**Describe the bug**
For some reason, [Redeemer's Mace](https://www.wowhead.com/item=177805) which is a (very) common Shadowlands world drop BoE is not disenchantable. At least not when using Molinari. I don't know why this is, I've looked through the code and couldn't find any reason it shouldn't be disenchantable. You will come across this item quite frequently though and it always stumps me having to manually disenchant it.

**How to reproduce**
Acquire Redeemer's Mace and try to disenchant it with Molinari.

**What did you expect?**
I would expect being able to alt-click it to disenchant, but it doesn't work.

**Comment by leobolin** [comment]
Also the same issue with [https://www.wowhead.com/item=4564](Spikied Club) (Classic world drop)

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/LibProcessable/commit/1dab8ca20baa40e0f9f8bc719c2a185b287eaf27
