### ISSUE TITLE
Tiny Titanium Lockbox ID appears incorrect

### ISSUE THREAD

**Issue by Repooc** [p3lim-wow/LibProcessable#45]
While checking the diffs between the lib version I was using to your current one (53), I noticed duplicated id used for Tiny Titanium Lockbox and Iron-Bound Junkbox of 106895, wowhead shows Tiny Titanium Lockbox as 45986.  I have not tested this in game, just going by wowhead data and the fact it was duplicate key in the table which didn't look intended

tldr; line 589, key should be 45986 for Tiny Titanium Lockbox if not mistaken

**Comment by p3lim** [comment]
Good catch, thanks for reporting!

**Comment by Repooc** [comment]
no prob, linter was yelling about it and figured it was an oversite lol
