### ISSUE TITLE
Flaw in :IsDisenchantable logic when using garrison building and items below level 21

### ISSUE THREAD

**Issue by Blazeflack** [p3lim-wow/LibProcessable#7]
By default GetSkillRequired returns "1" when quality is 2 and level is below 21.

When using the garrison enchanting building, this leads to :IsDisenhantable to return true for those items, when in fact low level items like that cannot be disenchanted at the garrison building.

**Comment by Blazeflack** [comment]
I modified the enchant building return to read
```
return skillRequired == 1 and not (quality == 2 and level < 21), skillRequired
```

Which solved it. I don't know if you have a better way to do it.

**Comment by p3lim** [comment]
Should have been resolved by now, most likely from one of these commits:
ffd2dee02d6a248f4ae327b3df0b1c196daf6a92
c36316ec8acab146eea2916d349f542a5639c1cd

Feel free to let me know if it's still not working correctly.
